# Generated by Django 2.2 on 2020-06-24 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_reverse', to=settings.AUTH_USER_MODEL)),
                ('home_list', models.ManyToManyField(related_name='fav_home', to='homeapp.Item')),
            ],
        ),
    ]
