# Generated by Django 2.2 on 2020-06-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rent',
            field=models.IntegerField(null=True),
        ),
    ]
