# Generated by Django 2.2 on 2020-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
