# Generated by Django 2.2 on 2020-06-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.FileField(null=True, upload_to='')),
                ('bedroom1', models.FileField(null=True, upload_to='')),
                ('bedroom2', models.FileField(null=True, upload_to='')),
                ('other', models.FileField(null=True, upload_to='')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='homeapp.Item')),
            ],
        ),
    ]
