# Generated by Django 2.2 on 2020-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bedroom1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='bedroom2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='kitchen',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='other',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
