# Generated by Django 2.2 on 2020-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20200627_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bedroom1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='bedroom2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='kitchen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='other',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
