# Generated by Django 2.2 on 2020-09-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20200627_0029'),
        ('homeapp', '0008_auto_20200627_0334'),
    ]

    operations = [
    ]
