# Generated by Django 2.2 on 2020-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_merge_20200912_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bedroom1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bedroom2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='other',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
