# Generated by Django 2.2 on 2020-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_auto_20200912_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
