# Generated by Django 2.2 on 2020-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_item_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
