# Generated by Django 2.2 on 2021-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_auto_20200915_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
