# Generated by Django 2.2 on 2021-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_auto_20210130_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
