# Generated by Django 3.0.8 on 2021-03-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_auto_20210130_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
    ]
