# Generated by Django 3.0.8 on 2021-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_auto_20210309_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
