# Generated by Django 3.0.8 on 2021-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_auto_20210312_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='name',
        ),
    ]
