# Generated by Django 3.0.8 on 2021-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_remove_extendeduser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
