# Generated by Django 3.0.8 on 2021-03-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_extendeduser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(default='Not Given', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.FileField(default='user.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(default='Not Given', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_number',
            field=models.CharField(default='Not Given', max_length=13, null=True),
        ),
    ]
