# Generated by Django 3.0.8 on 2021-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0019_auto_20210313_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.CharField(default='...', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='image',
            field=models.FileField(default='user.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(default='...', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_number',
            field=models.CharField(default='...', max_length=13, null=True),
        ),
    ]
