# Generated by Django 3.0.8 on 2021-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
