# Generated by Django 3.0.8 on 2021-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_auto_20210705_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
