# Generated by Django 3.0.8 on 2021-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0023_auto_20210705_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
