# Generated by Django 3.0.8 on 2021-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0025_item_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(default='Safe', max_length=200),
        ),
    ]
