# Generated by Django 3.0.8 on 2021-07-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0027_auto_20210705_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='availability',
        ),
    ]
