# Generated by Django 3.0.8 on 2021-07-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0029_item_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='otp',
        ),
    ]
