# Generated by Django 3.0.8 on 2021-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0030_remove_extendeduser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
