# Generated by Django 3.0.8 on 2021-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0031_auto_20210706_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
