# Generated by Django 3.0.8 on 2021-07-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0032_auto_20210706_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture3',
        ),
    ]
