# Generated by Django 3.0.8 on 2021-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0033_auto_20210706_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='otp_created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='otp_key',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='otp_used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
