# Generated by Django 3.0.8 on 2021-10-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0034_auto_20210816_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='longitude',
        ),
    ]
